{
    'name': 'Professional Portfolio',
    'version': '1.0',
    'category': 'Website',
    'summary': 'Professional Portfolio with NAICS Integration',
    'sequence': 1,
    'author': 'Kenneth Wyrick',
    'website': 'https://caltek.net',
    'depends': [
        'base',
        'website',
        'website_blog',
        'hr_recruitment',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/portfolio_views.xml',
        'views/naics_views.xml',
        'views/templates.xml',
        'data/naics_data.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
